# Generated by Django 5.1.3 on 2024-12-04 09:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('manager', models.CharField(help_text='kierownik akademika', max_length=200)),
                ('population', models.IntegerField(help_text='liczba mieszkańców')),
                ('room_count', models.IntegerField(help_text='liczba pokoi')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('tenant_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('type', models.CharField(choices=[('Jednoosobowy', 'Jednoosobowy'), ('Dwuosobowy', 'Dwuosobowy'), ('Trzyosobowy', 'Trzyosobowy')], max_length=200)),
                ('floor', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('rent_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dormitory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DormifyApp.dormitory')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('role', models.IntegerField(choices=[(0, 'Student'), (1, 'Manager'), (2, 'Administrator')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('student_status', models.BooleanField(default=True)),
                ('washes_number', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('room_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DormifyApp.room')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Przyjęto', 'Przyjęto'), ('W trakcie', 'w trakcie'), ('Zakończono', 'Zakończono')], default='Przyjęto', max_length=50)),
                ('title', models.CharField(help_text='tytuł zgłoszenia', max_length=200)),
                ('type', models.CharField(choices=[('naprawa', 'naprawa'), ('czyszczenie', 'czyszczenie'), ('inne', 'inne')], max_length=50)),
                ('content', models.TextField(help_text='szczegóły zgłoszenia')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DormifyApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=False)),
                ('date_payment', models.DateField()),
                ('payment_deadline', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DormifyApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_start', models.DateTimeField(help_text='Data i godzina rozpoczęcia prania')),
                ('reservation_end', models.DateTimeField(help_text='Data i godzina zakończenia prania')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DormifyApp.user')),
            ],
        ),
    ]
