# Generated by Django 5.1.4 on 2025-01-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormifyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='population',
            field=models.IntegerField(default=0, help_text='liczba mieszkańców'),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='room_count',
            field=models.IntegerField(default=0, help_text='liczba pokoi'),
        ),
    ]
