# Generated by Django 5.1.4 on 2025-01-20 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormifyApp', '0003_user_dormitory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='capacity',
            field=models.IntegerField(default=0, help_text='liczbba miejsc'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='washes_number',
            field=models.IntegerField(default=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
