# Generated by Django 5.1.4 on 2025-01-23 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormifyApp', '0004_dormitory_capacity_alter_user_student_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='dormitory_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DormifyApp.dormitory'),
        ),
        migrations.AddField(
            model_name='report',
            name='dormitory_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DormifyApp.dormitory'),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='capacity',
            field=models.IntegerField(default=0, help_text='liczba miejsc'),
        ),
    ]
