# Generated by Django 5.1.3 on 2025-01-23 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormifyApp', '0005_payment_dormitory_id_report_dormitory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundry',
            name='dormitory_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DormifyApp.dormitory'),
        ),
    ]
