# Generated by Django 5.1.4 on 2025-01-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormifyApp', '0006_laundry_dormitory_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_deadline',
        ),
        migrations.AddField(
            model_name='user',
            name='is_payment_paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
